#!/bin/sh
#
# Last Modified: 2025-Jul-29
#
# shellcheck disable=SC2039 disable=SC3043
#
trap '' HUP

readonly VERSIONstr="3.4.10"
readonly logTagStr="timeserverd_[$$]"

##-------------------------------------##
## Added by Martinski W. [2025-Jul-27] ##
##-------------------------------------##
WaitFor_NTP_Ready()
{
    local theSleepDelay=15  ntpMaxWaitSecs=600  ntpWaitSecs

    [ "$(nvram get ntp_ready)" -eq 1 ] && return 0

    ntpWaitSecs=0
    logger -st "$logTagStr" "Waiting for NTP to sync before starting..."

    while [ "$(nvram get ntp_ready)" -eq 0 ] && [ "$ntpWaitSecs" -lt "$ntpMaxWaitSecs" ]
    do
        sleep "$theSleepDelay"
        ntpWaitSecs="$((ntpWaitSecs + theSleepDelay))"
        if [ "$((ntpWaitSecs % 30))" -eq 0 ]
        then
            logger -st "$logTagStr" "Waiting for NTP to sync [$ntpWaitSecs secs]..."
        fi
    done

    [ "$ntpWaitSecs" -ge "$ntpMaxWaitSecs" ] && return 1
    logger -st "$logTagStr" "NTP has synced [$ntpWaitSecs secs]."
    return 0
}

if ! WaitFor_NTP_Ready
then
	logger -st "$logTagStr" "NTP failed to sync after 10 minutes - please check immediately!"
	exit 1
fi

if [ -f "/opt/share/ntpmerlin.d/config" ]
then
	SCRIPT_STORAGE_DIR="/opt/share/ntpmerlin.d"
else
	SCRIPT_STORAGE_DIR="/jffs/addons/ntpmerlin.d"
fi

##-------------------------------------##
## Added by Martinski W. [2025-Jul-16] ##
##-------------------------------------##
_IsZombieProcess_()
{
    if [ $# -eq 0 ] || [ -z "$1" ] || ! echo "$1" | grep -qE "^(ntpd|chronyd)$"
    then return 1 ; fi

    local theProcStr  thePIDnum  thePPIDnum  logMsg

    theProcStr="$(/usr/bin/top -bn 1 | grep -w "$1" | grep -v "grep" | awk -F ' ' '{if ($4 == "Z") print $0}')"
    if [ -z "$theProcStr" ]
    then return 1  #Process OK#
    fi

    thePIDnum="$(echo "$theProcStr" | awk -F ' ' '{print $1}')"
    thePPIDnum="$(echo "$theProcStr" | awk -F ' ' '{print $2}')"
    logMsg="$(printf "A zombie '$1' process was found [PID=%d, PPID=%d]" "$thePIDnum" "$thePPIDnum")"
    logger -t "$logTagStr" "$logMsg"

    if [ -n "$thePPIDnum" ] && [ "$thePPIDnum" -gt 2 ]
    then
        kill -TERM "$thePPIDnum"
        wait "$thePPIDnum"
        if kill -EXIT "$thePPIDnum" 2>/dev/null
        then
            kill -KILL "$thePPIDnum"
            wait "$thePPIDnum"
        fi
    fi

    return 0
}

##----------------------------------------##
## Modified by Martinski W. [2025-Jul-29] ##
##----------------------------------------##
if [ "$1" = "S77ntpd" ]
then
	if [ -f /opt/etc/init.d/S77chronyd ]
	then
		/opt/etc/init.d/S77chronyd stop >/dev/null 2>&1
		sleep 2 ; killall -q chronyd ; sleep 2
		rm -f /opt/etc/init.d/S77chronyd
	fi

	ntpd -c "$SCRIPT_STORAGE_DIR/ntp.conf" -g > /dev/null 2>&1 &
	logger -t "$logTagStr" "ntpd was started"

	while true
	do
		sleep 5
		if [ "$(pidof ntpd | wc -w)" -eq 0 ] || _IsZombieProcess_ ntpd
		then
			logger -t "$logTagStr" "ntpd dead, restarting..."
			ntpd -c "$SCRIPT_STORAGE_DIR/ntp.conf" -g > /dev/null 2>&1 &
			logger -t "$logTagStr" "ntpd was restarted"
		fi
	done

elif [ "$1" = "S77chronyd" ]
then
	if [ -f /opt/etc/init.d/S77ntpd ]
	then
		/opt/etc/init.d/S77ntpd stop >/dev/null 2>&1
		sleep 2 ; killall -q ntpd ; sleep 2
		rm -f /opt/etc/init.d/S77ntpd
	fi

	if [ -f /opt/etc/init.d/S06chronyd ]
	then
		/opt/etc/init.d/S06chronyd stop >/dev/null 2>&1
		sleep 2 ; rm -f /opt/etc/init.d/S06chronyd
	fi

	mkdir -p /opt/var/lib/chrony
	mkdir -p /opt/var/run/chrony
	chmod -R 770 /opt/var/lib/chrony
	chmod -R 770 /opt/var/run/chrony
	chown -R nobody:nobody /opt/var/lib/chrony
	chown -R nobody:nobody /opt/var/run/chrony
	[ ! -L /opt/etc/passwd ] && \
	ln -snf /etc/passwd /opt/etc/passwd 2>/dev/null

	chronyd -r -u nobody -f "$SCRIPT_STORAGE_DIR/chrony.conf" > /dev/null 2>&1 &
	logger -t "$logTagStr" "chronyd was started"

	while true
	do
		sleep 5
		if [ "$(pidof chronyd | wc -w)" -eq 0 ] || _IsZombieProcess_ chronyd
		then
			logger -t "$logTagStr" "chronyd dead, restarting..."
			chronyd -r -u nobody -f "$SCRIPT_STORAGE_DIR/chrony.conf" > /dev/null 2>&1 &
			logger -t "$logTagStr" "chronyd was restarted"
		fi
	done
fi
